web:
  build: .
  links:
    - database:database
  ports:
    - "3000:3000"
  environment:
    RAILS_ENV: production
    SECRET_KEY_BASE: somesecretkeyforrails
    MYSQL_PASS: somesecretpassword
    MYSQL_USER: root
database:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: somesecretpassword