#!/bin/bash

set -e

cd /usr/src/app

MYSQL_HOST=$DATABASE_PORT_3306_TCP_ADDR
MYSQL_PORT=$DATABASE_PORT_3306_TCP_PORT

MYSQL="mysql -h$MYSQL_HOST -P$MYSQL_PORT -u$MYSQL_USER -p$MYSQL_PASS"

if [ ! $($MYSQL -e 'show databases;'| grep ^app$) ]; then
  $MYSQL -e "create database app;"
fi

rake db:migrate

exec rails s $*
